vich_uploader:
    db_driver: orm

    mappings:
        player_image:
            uri_prefix: /images/player
            upload_destination: '%kernel.project_dir%/public/images/player'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

        type_image:
            uri_prefix: /images/type
            upload_destination: '%kernel.project_dir%/public/images/type'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
